spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/prmo
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      schema: prmo_schema
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 10000
      pool-name: HikariCP
      max-lifetime: 1800000
      connection-timeout: 30000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

